### ISSUE TITLE
(openComputer) reactor.getControlRodLevel(0) always returns "nil"

### ISSUE THREAD

**Issue by krakaen** [ZeroNoRyouki/BigReactors#137]
When we do a reactor.getControlRodLevel(0) as of version 1.10.2-0.4.5.41, we get "nil" from the reactor, I know you made the code more modular, but did something change or break?
The program works on older versions of Extreme Reactor.

I have been using my program for some time already, a lot of people are reporting that it is not working and every time, they are on a version above 0.4.5.41 or on it

**Comment by ZeroNoRyouki** [comment]
There is a problem in .41 that prevent the computer port to rejoin the OC network correctly (see #134) but it's already fixed in .42+

Keep in mind that the computer port join (and leave) the network when it is attached (or detached) from the multiblock controller (not the block, the actual control class of the reactor) so it could be a good idea  not to assume that the component is always there and it is talking to the actual controller of the reactor (this could cause some strange values returned from the port methods because you are actually talking to another multiblock controller if the port get separated from the original controller)

In my todo list there are a bunch of new methods to check the state of the generic multiblock structure so you guys could check if, for example, the reactor is assembled before getting values from it. I'll see if I could push this up a bit in the queue. Tonight I will push out another release to fix yet another problem with OC and the Turbine (...) so maybe I could splip in an "is assembled" method. We'll see

**Comment by krakaen** [comment]
They issue does seem to be only for the getControlRodLevel. When i use other method, it works fine and does not throw an error this is the only one that does it for me

**Comment by ZeroNoRyouki** [comment]
Try another method that require a parameter. You should get the same error

**Comment by ZeroNoRyouki** [comment]
.44 is out and it includes both the Turbine/OC fix and a new method to detect if the multiblock is assembled or not (getMultiblockAssembled)

**Comment by ZeroNoRyouki** [comment]
Does the update solve your problem?

**Comment by krakaen** [comment]
oh, sorry, i forgot to answer, yes it does, thanks a lot :)
