### ISSUE TITLE
method reactor.setControlRodsLevels() not always working properly 

### ISSUE THREAD

**Issue by krakaen** [ZeroNoRyouki/BigReactors#180]
I have a program with openComputer that seem to work 75% of the time and It seems there is an issue with the method setControlRodsLevels.

I have 2 images here, one shows it working and one not working, Both pass the getControlRodsLevels method return directly to the setControlRodsLevels method.

both are in the same modpack (revelation 2.0.0) with the same version of the mod : 1.12.2.0.4.5.49

Both reactor are made so that the rods are in mutliple chunks

Working
![working-lua-extreme-reactor](https://user-images.githubusercontent.com/8230693/41385706-57cb1d84-6f4b-11e8-830e-927bfcf49deb.jpg)

Error
![error-lua-extreme-reactor](https://user-images.githubusercontent.com/8230693/41385711-5f8a7718-6f4b-11e8-9e2b-e279b8ff3e83.jpg)

At this moment, I cannot use the setControlRodsLevels method as it is not reliable. Could you check if there is something wrong in the code? the images above are not even in the code, they are just simple LUA commands.

Thanks

**Comment by ZeroNoRyouki** [comment]
Hi there, this may be related to https://github.com/MightyPirates/OpenComputers/issues/2319

In the "LUA portion" of that method I just iterate over the table to make a copy of it before returning to LUA. This is done before the code of setControlRodsLevels actually run

**Comment by krakaen** [comment]
this issue dates from a year ago... 
I do hope you do not plan on removing the old methods anytime soon as it will mean, most people won't be able to make any program to control the reactor. I am not even sure what to do here... Using the old method can become deprecated any time soon and using the new one brings issues that I cannot do anything about.

**Comment by ZeroNoRyouki** [comment]
Don't worry, setControlRodLevel is not going away. If you need to change a single control rod, that's the method to call. setControlRodsLevels is there if you need to change more than one rod in a single call (and speed things up on your side)

I need to make a copy of the table because of a race condition between the LUA thread that own the table and MC server thread that actually run the code of setControlRodsLevels (and any other set/do methods)

**Comment by krakaen** [comment]
I found a way to use setControlRodLevel in a loop to fill the rods, It is a bummer that we can't use the new method to change all of them. When I was talking about the old ones, I mainly meant (setAllControlRodLevels) but using setControlRodLevel seems to do what i need :) 
thanks for the help should I post that issue on the openComputer github? maybe it could help them?

**Comment by krakaen** [comment]
I belive it was the lastest version of it, I was testing in the lastest version of FTB Revelation. But this happens to some and not to others. I was fine when I tested it in SP, but I went on a viewers server and he was getting that error... I can't explain why...

When printing the informations on my program screen, he also had decimals to the shown numbers while I had none in SP...

All this with the same program..

**Comment by asiekierka** [comment]
@ZeroNoRyouki You should only have race condition issues if you're doing direct=true, no? If direct=false, then the method should be called on the MC thread, if I remember correctly? https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/java/li/cil/oc/api/machine/Callback.java#L44-L50

**Comment by ZeroNoRyouki** [comment]
@asiekierka: I have an Environment that implement ManagedPeripheral which basically means that all my methods are called by the LUA thread, like the a direct=true Callback

To make things thread-safe, I schedule the actual code of the methods that change the internal state of a machine or interact with the world to run on the MC thread. The OC'implementations of Maps and Lists contains a sync lock and that's where the race condition come from. I've got reports of timeouts firing up on the MC thread because one of my methods was struck waiting on a Map::size() call. To avoid this I now make a copy of all parameters when ManagedPeripheral::invoke is called on the LUA thread.

From what I can see, this looks like a problem with the iterator of the Arguments implementations

**Comment by ZeroNoRyouki** [comment]
@krakaen : I was testing a different implementation of the code that is making copies of the methods arguments and it's looking good.

Could you please check it too ?

[zerocore-1.12-0.1.2.3-pre-ocfix.jar.zip](https://github.com/ZeroNoRyouki/BigReactors/files/2166898/zerocore-1.12-0.1.2.3-pre-ocfix.jar.zip)

**Comment by asiekierka** [comment]
Could you show me the code instead? I'm more likely to find issues that way than through in-game bugtesting.

**Comment by ZeroNoRyouki** [comment]
@asiekierka : here you go:

https://pastebin.com/wjjrvY1R

That's the ManagedPeripheral. The exception reported by @krakaen is raised in the iteration at line 119

**Comment by ZeroNoRyouki** [comment]
@krakaen are you still experiencing this problem?
