### ISSUE TITLE
Reactor producing power even in unloaded chunk

### ISSUE THREAD

**Issue by Jason505** [ZeroNoRyouki/BigReactors#188]
Hey there!
I'd like to know, if there is an option to auto turn off reactors in non-loaded chunk. Every second player on our server has this reactor and it's one of the perfomance problems on server side.

Thanks,
Jason505

**Comment by ZeroNoRyouki** [comment]
Hi,
a Reactor (or a Turbine, or any other machine in Minecraft) cannot work if the chunks that contains it are not loaded. It's a basic Minecraft mechanic. So if those Reactors are indeed working then those chunks are actually loaded, by a chunk-loader block or because they are in the spawn region or other external factors

**Comment by Jason505** [comment]
So, the reactor itself doesn't load chunk? Well, that means we have to analyse 87 other mods and find which block does it cause.
Thanks anyway.

**Comment by ZeroNoRyouki** [comment]
Yup, I have no chunk loaders in the mod.

I'm closing this for now, if you have any further questions fell free to add them here
