### ISSUE TITLE
Power tap attempts to push RF into EnderIO capacitor bank multiple times per tick

### ISSUE THREAD

**Issue by pha3l** [ZeroNoRyouki/BigReactors#201]
When placing an EnderIO capacitor bank directly adjacent to a power tap, an explosion sound  and animation occurs.  The power tap is attempting to send FE twice per tick (a problem which the EnderIO devs seem to have cheekily handled with the explosions) due to the following code:

```java
    long energyAvailable = getEnergyStored();
    long energyRemaining = energyAvailable;
    long splitEnergy; 
    if ((this.attachedPowerTaps.size() > 0) && (energyRemaining > 0L))
    {
      splitEnergy = energyRemaining / this.attachedPowerTaps.size();
      for (TileEntityReactorPowerTap powerTap : this.attachedPowerTaps) {
        if (energyRemaining <= 0L) break;
        if (powerTap.isConnected())
        {
          energyRemaining -= splitEnergy - powerTap.onProvidePower(splitEnergy);
        }
      }
      
      if (energyRemaining > 0L) {
        for (TileEntityReactorPowerTap powerTap : this.attachedPowerTaps) {
          if (energyRemaining <= 0L) break;
          if (powerTap.isConnected())
          {
            energyRemaining = powerTap.onProvidePower(energyRemaining);
          }
        }
      }
    }
```

So, if there's only one tap and it doesn't accept the entire amount in the first provide, it will attempt to send the remaining power in the same tick.

**Comment by tterrag1098** [comment]
For the record, I understand the goal of this code, but the implementation breaks many many assumptions about power systems. You should be using `simulate = true` to check how much each power receiver can take, then you can split evenly without pushing multiple times.

**Comment by ZeroNoRyouki** [comment]
Sorry for the late replay but I'm working on 1.13 right now. I'm changing this to split the amount of energy available between the connected providers, without the second attempt. The providers will try to push their share of energy to the connected power receiver (I'm not simulating it because I don't need to known the accepted amount beforehand, I just need to get the amount of energy actually accepted). So in the end, you may need more power taps to get all the energy stored in the internal buffer of a Reactor or Turbine if the connected power receivers have a low energy flow rate.

**Comment by ZeroNoRyouki** [comment]
Changed in 1.12.2-0.4.5.66
