### ISSUE TITLE
[1.10.2] Server Crash placing a Mekanism universal cable against the reactor power tap.

### ISSUE THREAD

**Issue by ProsperCraft** [ZeroNoRyouki/BigReactors#24]
https://github.com/aidancbrady/Mekanism/issues/3853

**Comment by ZeroNoRyouki** [comment]
Could you please check it using ER 1.10.2-0.4.5.17 ? (released today)

**Comment by codewarrior0** [comment]
Don't have the crash log, but I got this crash in 0.4.5.17 when placing a mek cable against a *Turbine* power tap.

**Comment by RealGrep** [comment]
Yep, I've also had that crash. I went back and found the crash report for it, in case that's useful to you. Basically, attaching the Mek universal cable to the turbine RF power tap, and instant server crash. They have not caused any crashes hooking them up to numerous other things, so far. Though I suspect the Mek cables need some attention and wouldn't be surprised if the real fault lies there.

The crash report: http://hastebin.com/vutajepeco.sql

And this is with ExtremeReactors-1.10.2-0.4.5.17.jar. I believe I had Forge 2095 at the time.

**Comment by RogueLogic** [comment]
The stack trace point to Mekanism, please submit a issue there to attempt to remedy this issue. if the issue is in fact an Extreme Reactors issue Zero needs to know the exact cause of the error to be able to fix it. and to be noted the there are two power tap handlers the RF/FU one and the Tesla one. This information is vital as the inter workings of the APIs are completely different.

**Comment by ZeroNoRyouki** [comment]
Fixed. lt will be included in the next release

**Comment by RealGrep** [comment]
Yep, looks good. Updated, and tested it first thing. Put an ultimate universal cable against the turbine power tap. No crash. Turbine blades also oriented correctly. Thanks!
