### ISSUE TITLE
Cyanite Ingot to Blutonium

### ISSUE THREAD

**Issue by Minecraft-Space** [ZeroNoRyouki/BigReactors#27]
The recipe to create Blutonium is incorrect and makes my reactors suffer. Usually you would only need 2 Cyanite ingots to create Blutonium, but 8 is just crazy now. Please change the crafting recipe to only use 2 per Blutonium. (I know you are adding a machine in a future version, but for now, this is just way too expensive)

A possible solution is adding a new 'Recipe' option to the config to enable/disable this. It can be disabled by default to have your 8 ingot behaviour.

Thanks,
MCSpace

**Comment by RogueLogic** [comment]
I'm guessing you want it for reactor refueling, not turbine controllers?

**Comment by Minecraft-Space** [comment]
Yes, that is absolutely correct. I would like to recycle my fuel like in the original mod, so that I don't have to go mining for Yellorite as often.

**Comment by RogueLogic** [comment]
a) build a turbine. b) @ZeroNoRyouki c) create a custom jar, fine if this is single player. in order of recommendation. afaik Blutonium was never meant to be reactor fuel as it was.

**Comment by Minecraft-Space** [comment]
I'm sorry, but the instructions aren't too clear. Could you please create a better list of instructions? I'd really appreciate that =)

**Comment by RogueLogic** [comment]
To solve you problem ( constantly mining for yellorium) could either
A) build a turbine,
B) make a more efficient reactor,
C) use a computer to control your reactor,
D) use a quarry,
E) compile a ER.jar with a modified recipe (I could help you with this).

Obv, you can combine any and all of the solutions listed.

**Comment by Minecraft-Space** [comment]
Oh, I get it now. Sorry, I thought that was a continuous list and that I had to do those steps in order. Thanks for the help, really appreciate it =) (I'm sure I can easily do [F] myself.)

**Comment by Flukey** [comment]
I guess someone has to make the decision whether or not blutonium *should*
be used as a fuel or not. And if not, what is the use for blutonium?

http://wiki.technicpack.net/Blutonium_Ingot

The above states that it was intended to be used as fuel, and that's how
I've always known it to work.

On 10 Oct 2016 22:57, "RogueLogic" <notifications@github.com> wrote:

a) build a turbine. b) @ZeroNoRyouki <https://github.com/ZeroNoRyouki> c)
create a custom jar, fine if this is single player. in order of
recommendation. afaik Blutonium was never meant to be reactor fuel as it
was.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ZeroNoRyouki/BigReactors/issues/27#issuecomment-252757052>,
or mute the thread

**Comment by ZeroNoRyouki** [comment]
Blutonium can be used as fuel in the reactor if you like, right now.

Making a more efficient reactor FOR YOUR NEEDS is what you should do. So not THE most efficent reactor, but the best one for what you need at the moment
You need more cynite? Build a reactor that produce a lot of it

Turbines are a good alternative for power production

Other builds of the mod will get no support whatsoever. If you know how to make a mod, what you could do is create one that add new fuels for the reactor. The is an API for that

Z

**Comment by RogueLogic** [comment]
Want to make sure this is clear. I did not recommend a custom jar just said it was an option, hence I listed it at the bottom. Also as Zero said bluetonium is a reactor fuel, but E.Beef did not want it to be identical to yellorium. You can even find this in the source as a TODO.
