### ISSUE TITLE
Config Request

### ISSUE THREAD

**Issue by Mattabase** [ZeroNoRyouki/BigReactors#36]
I would love the option to set what block/liquids do to the reactors. Cooling wise ect, any chance that could be a thing?

**Comment by ZeroNoRyouki** [comment]
Nop :)

The idea here is to play with the mod, experiment with blocks and fluids to find the best one for your needs

**Comment by Lanse505** [comment]
I think this is less about people being able to "Find the optimal liquids/blocks" and more about allowing Pack Authors to add greater compatability between mods in their packs.

For example this would be "HUGE" together with some of the upcoming features in BASE. 
Since with BASE you'll be able to add Custom Blocks and Liquids later on.

Allowing for Pack Authors together with an option like this to add their own liquids and liquid support for greater intercompatability within the pack and a good clear progression.

**Comment by RogueLogic** [comment]
do you understand how hard what you just described would be?

**Comment by Lanse505** [comment]
Since I'm one of the Devs for Base, the adding of custom liquids and blocks is something on our docet and something we will be doing. So that's not hard.

The Adding of "Extreme Reactor" Values to specific new blocks really depends on how ExtremeReactors codes in their values for cooling and such. Like nothing is impossible.

If @ZeroNoRyouki does decide to go through with this he knows where he can go for help (Modders Corner) and we'd try and help all we can. 

Look all I'm saying is @Mattabase and Mine's argument isn't one of "Yea we need to tweak things cause reasons". It's literally just a request to help increase inter-mod compatbility which would make Extreme Reactors more usable and configurable.

**Comment by ZeroNoRyouki** [comment]
@Lanse505 there is already an API for that. Other mods can add their block/fluids to the Reactor moderators and blocks to be used as coils for the Turbine

@RogueLogic : it would not be that hard technically

**Comment by Lanse505** [comment]
Well yea @ZeroNoRyouki but that doesn't help Pack Authors though.
Configs would be for Pack Authors so they can add "coil validity" or Block/Liquid support to Reactors.

Like for example lets say someone does a Magic/Tech pack with a larger focus on the Magic part.
I as a pack author might decide "Hey, Void Metal from Thaumcraft should be a valid coil material"
With only the API they have no way of doing this without a custom mod handling the api for them.
With an Config they could simply add it through there..... Well "Simply" 

If a config set-up is not on the table.
Would you be okey with someone else making an addon or something todo this.
Cause tbh, it'd be a great feature for Pack Authors looking for more power over the mod and for powerful cross-mod support.

**Comment by ZeroNoRyouki** [comment]
Generally speaking, no. 

I don't want players to be able to add fuels/moderators/coils by themselves. We would end up with reactors powered by dirt. 

Making a mod that use the API is not that hard, so a Pack Author can make one without too much work. And with a config based mod/pack the player could also change the behavior of the pack in a way that was not intended by the pack author
