### ISSUE TITLE
Config option to remove update notification message

### ISSUE THREAD

**Issue by BinaryCrafter** [ZeroNoRyouki/BigReactors#51]
This apples to both ExtremeReactors, and ZeroCore.

I have a modpack which includes your mod (thanks for your hard work), but my modpack has been carefully created to ensure no mod generates any world load chat message. I've even gone to the extent of avoiding certain mods completely where necessary to to achieve this.

I saw you recently added this version checking feature in a recent changelog, and I can keep my modpack using an older version of ExtremeReactors, but would prefer to keep updating to capture any new features/bug fixes that are added.

Please would you consider adding an option to completely disable this behaviour, as players who use mod packs (most players), won't care for these messages, as the updates are managed by the modpack creator.

p.s. I don't know if you're aware, but there is a feature that's part of forge designed for providing users with update notifications, without having to resort to spamming chat.

**Comment by Darkosto** [comment]
Yes, I will ask for this once more. Please add this option. SkyFactory 3 has been packaged for release and the first thing players are going to see when they open a world is that Extreme Reactors has an update.

**Comment by RogueLogic** [comment]
Now I'm going to hag on Zero a bit here. This issue was created 27 days ago (at time of writing), takes one additional config option (boolean, the simplest) and a single if statement, or about 5 minutes, max. Now if for some reason this in an excessive amount of work to be done someone here may know how, oh but Zero (or ABookFreak now that he is added) hasn't updated the repo for 3 months now. Looks like I can't fix a simple issue for him, again.

PS: Darkosto, looking forward to SF3 and great job on 2.5.

**Comment by ZeroNoRyouki** [comment]
@BinaryCrafter  / @Darkosto : we are still debating this request and how much controll give to the user if we end up implementing it. Being able to notify a fix for a showstopper is very important to us so what we are probably going to do is implement a priority system in our backend and allow the player to filter out low-priority notifications (such as new features and minor bugs)

@RogueLogic : your 5 minutes PR would have been rejected for the reason above. Don't assume that what you would do is what we would do. Your time is probably better spent working on your projects

**Comment by SephirothWS** [comment]
@ZeroNoRyouki Well stop debating and implement the feature request. When a modpack developer puts together a pack for release, it should be up to the modpack developer to provide updates to that pack. End-users shouldn't have to worry about such a thing, and this is why most mods give the option to disable update notifications to begin with. So what you want to notify about a fix for a showstopper? That doesn't mean modpack developers don't want to have update notifications plaguing their in-game chat first thing whenever they open the pack.

**Comment by Quetzi** [comment]
I'd go further and say the config option should disable the check completely. There are very, very few cases where such a check/message is useful for the end user.

**Comment by ZeroNoRyouki** [comment]
After talking with Darkosto about this, we decided to disable the notification check for now. A config option would be added in one of the next releases

@Quetzi: are you saying that the tipical end user is incapable of updating it's client / mod pack? If that's so, why bother with the notification in the first place?

**Comment by Quetzi** [comment]
Exactly my point. It's not so much that they are incapable of updating, but more that they can't update ahead of their Modpack does because it will prevent server play. Those users that do play custom DIY packs will either use Curse to update each mod as it becomes available or update all the mods in a batch, rather than when each individual mod complains about an update. 

I'll concede that there are a small number of users that find them useful, but the rest shouldn't have the overhead of a web check added to their startup (even if it is a separate thread)

**Comment by ZeroNoRyouki** [comment]
Message removed
