### ISSUE TITLE
Update github code?

### ISSUE THREAD

**Issue by MakeLord95** [ZeroNoRyouki/BigReactors#64]
Could you update the code here?

**Comment by ZeroNoRyouki** [comment]
we no longer use GitHub as our VCS

**Comment by MakeLord95** [comment]
Do you guys still do open source?

**Comment by RogueLogic** [comment]
If that is the case Zero, please act more professional instead of just closing my issue about this for ZeroCore. ZeroNoRyouki/ZeroCore#4
similar story with ZeroNoRyouki/BigReactors#51 and ZeroNoRyouki/BigReactors#40 you could have at least acknowledged that the issues/requests exist instead of not responding. even something to the tune of "we will have to think about it" or "we are discussing it" is better than silence. especially for what has it been now, over two months.

Having access to your a current ZeroCore repo is very important to me seeing as i am making a mod dependent on it. Would you kindly link me to the current repo. A current ER repo would also be much appreciated as i have an idea of how to fix ZeroNoRyouki/BigReactors#59 but cannot even attempt as i do not have the latest version. If you feel like telling me off, i don't really care. My time is my time, if i choose to spend it fixing my favorite mod (completed that is) that's my choice.

**Comment by ZeroNoRyouki** [comment]
We are using one of the VCS server of my company. It's not public. My maven rep is up-to-date

**Comment by RogueLogic** [comment]
Why? also i could not find a ER repo.

**Comment by Robertof** [comment]
+1. Even if you moved the main repo to a private VCS repo, please keep the code updated on GitHub, as it was in the beginning. You could use [multiple remotes](https://help.github.com/articles/adding-a-remote/) to sync the code between your VCS and GitHub, and if you don't like user contributions, you may even disable pull requests. But I'd really appreciate to see Extreme Reactors open sourced.
