### ISSUE TITLE
No updates to code despite new mod releases

### ISSUE THREAD

**Issue by MikrySoft** [ZeroNoRyouki/BigReactors#74]
I would really like to see some action on this repo, since for many people (like me) reading code is the easiest/fastest way of learning how the mod works and how to min/max it, not to mention people trying to write companion software.

I did read in one of the issues that the development was moved to a private repo, but git can easily push to multiple remotes (see  http://blog.deadlypenguin.com/blog/2016/05/02/git-push-multiple-remotes/ for example).

If there are other reasons for effectively closing source of the mod, I can understand that, but if convenience is the only thing driving that decision, the link above should provide solution for both sides.

I really hope this great mod can stay open source.

**Comment by RogueLogic** [comment]
Can't speak for Zero but my school has a private gitlab server that i have some projects on and it is less convenient to use it than GitHub is, especially with IntelliJ (the IDE both me and Zero use) has amazing integration. Even if the code here is only updated when there is an new release that would be miles better than this bullshit.

Companion software MASSIVLY benefits from source, _shameless plug for [BigFusiuon](https://github.com/RogueLogic/Big-Fusion)._ In the process of building my mod (BigFusion) using ZeroCore I have questions about things that i cannot answer because I do not have access to the latest source and Zero is anything but reliable for contact.

@ZeroNoRyouki Please respond to this professionally and not act like a child as you have in the past.

**Comment by ZeroNoRyouki** [comment]
@MikrySoft: the thing is I don't want people to min/max it on the fly by, like you said, checking how the code works. I want them to experiment in game, while, maybe, having it blowing up in the process :). That's why, for example, there is now way to get a list of reactor moderators or turbine coils (in-game or by code). And you should never code your software based on the implementation details of the one you are interacting with: that's what a public interface is for

@RogueLogic: I concur on what you are saying about gitlab, that's why I'm not using it either. A professional lab is way better than github / gitlab / whatever. I give you the same bit of advice about implementation details: don't relay on them. If you have questions about how to use Zero CORE ask away, like you did many times in the past. You can find me on MMD/Tesla discord servers.

I'm not going to respond to any other similar issues. Like RogueLogic hinted, I don't have that much free time.

Z

PS: I checked the link you posted RogueLogic, you should probably add a .gitignore file to your repo
