### ISSUE TITLE
Reactor/Turbine using a stupidly high amount of water

### ISSUE THREAD

**Issue by Anaerin** [ZeroNoRyouki/BigReactors#87]
Even with turbines set to return all the water used in active cooling, I cannot keep up with the water demands of my reactor.

I have a single reactor producing exactly 2000mb/t of steam, feeding into a turbine using all of that steam and set to return all the water, and even with all that set, 24 ExU2 fluid transfer nodes with mining upgrades and 20 speed upgrades each (producing ~2400mb/t IIRC) can't keep up with the demands.

In previous versions, it didn't need this much - 100mb/t was enough to keep things topped off, but for some reason this latest update the usage is crazy high.

Direwolf20 modpack v 1.6.1 (was perfectly fine in 1.5.1).
Mod version: 0.4.5.26
Forge version: 12.18.3.2185

**Comment by ZeroNoRyouki** [comment]
Water usage has not changed. Replace the mining upgrade with a stack upgrade

**Comment by RogueLogic** [comment]
Better question, how are the reactor and turbine connected?

**Comment by Anaerin** [comment]
The reactor is right next to the turbine, connected with input and output valves next to the appropriate output and input valves on the turbine. And as mentioned, in previous versions this was working perfectly.

Also, stack upgrades do nothing in fluid transfer nodes, I tested. Using an RS Exporter, with 1 stack upgrade and 3 speed upgrade, I can keep the water level in a single reactor/turbine high enough to use, but as mentioned I have 24 maxed out fluid transfer nodes (the fastest fluid creation block in this pack) feeding water into the RS system, and it's not enough to stop the internal fluid levels from dropping.

**Comment by icedown** [comment]
After much playing around with things, I believe this problem and #89 are part of the same issue.  I have a 9x9x9 turbine, internal size 7x7x7 with control rods in checkerboard pattern with air in the other spaces.  It has 4 9x9x15 turbines attached directly to it.  I have not been able to pin down anything consistent in the problem except that it is worst right after a server reboot.  I believe it has something to do with the turbines rather than the reactor.  

I did a whole bunch of trial and error tests and results were completely inconsistent to say the least. Trying all kinds of turbine on/off combinations.  I had issues with running out of fluid, lack of steam generation past certain but inconsistent temps.  Even with all 4 turbines on it would not produce more than 2,000mb/t one time,  cooldown and restart I was able to get it to 4000 and be stable.  After breaking the reactor, rebuilding it, setting all turbine vents closed, I was able to get somewhere.  

After a little and at a 99% rod setting, i was able to bring 1 turbine online and it worked fine.  Brought the rods to 92% and the first turbine reached full steam with 2000mb/t output on the reactor. starting each turbine in turn and leaving the vents closed, while pulling the control rods further for each turbine I was able to bring each turbine online.   During this time fluid levels stayed manageable.  If I set a turbine to vent all, it would rapidly empty the system.    

During this whole start up, i realized that while all of the turbines showed 1/2 tank of steam, none of the showed any water in the tank.  After a little bit in operation, one of them started slowing down and that's when I realized it had filled up with both steam and water.   I turned the valve back to vent overflow and it began operating properly with both tanks at 1/2.  All of the other turbines at this time are still operating normally with vents closed and only showing 1/2 tank of steam and no water.  

Finally to what I suspect may be part of the problem.   I think the water tanks in the turbines are actually going negative.  Since I haven't had another turbine fill up yet I can't confirm it but if I do I will post again.  I may be way off on this but hopefully it will help you pinpoint the issue.

**Comment by RogueLogic** [comment]
@Anaerin could you provide a world download, _usually easier than asking for specific information._ 
This issue may have something to do with chunk load order, as #59 did and #89 is related to.

**Comment by Anaerin** [comment]
Here you go. The barest minimum required to show this bug. In previous versions, even with the turbine in dump mode, the turbine and reactor would generate and use almost exactly 2000mb/t. Now the turbine requires considerably more (as you can see from the 4 maxed out fluid transfer nodes - It's set to closed loop, so it shouldn't need to be constantly refilled like this, and it appears to be using 10,000mb/t of water.
[Reactor Derp.zip](https://github.com/ZeroNoRyouki/BigReactors/files/846741/Reactor.Derp.zip)

**Comment by RogueLogic** [comment]
I downloaded and testes that world with only Extra Utilities 2 (1.3.3), Extreme Reactors (0.4.5.26), and ZeroCore 0.1.0.4 and this problem was no where to be seen, #59/#89 however poked it's fat head back up again.

**Comment by ZeroNoRyouki** [comment]
Hi, please check ER 0.4.5.29, it close #89
