### ISSUE TITLE
Reactor will not produce more than 2000mb/t of steam

### ISSUE THREAD

**Issue by patrix87** [ZeroNoRyouki/BigReactors#99]
I'm not sure if that is the intended design or not, but it does not matter how many coolant ports, turbines, and fuel rod that you put in a reactor.

It will never output more than a total of 2000mb/t of steam. Which is just enough for one 80 blades turbine.

If that is the intended design I think that it would be nice to not be limited for three reasons.

1. Being limited prevents users from seeing the actual steam production of the reactor therefor most of the time producing way more than required.

2. A lot of FTB mod packs uses Extreme Reactor and FTB is not a place where moderation and small builds are common. More is better.

3. Connecting multiple turbine to the same reactor would be more efficient.

**Comment by BrisingrAerowing** [comment]
I have noticed this myself. It seems that the original Big Reactors could output a lot more than 2000 mB / T of steam, from what I gathered from a tutorial on the original mod that I watched, so I would guess it's a bug.

**Comment by ZeroNoRyouki** [comment]
It does not work that way. Basically, an actively cooled reactor can produce up to 50.000 mB of steam (depending on it's volume). The reactor coolants ports transfer rate is limited only by the amount of fluid available (output) or by the free space in tank (input). It's the Turbine input rate that it is (and was in Big Reactor) capped to 2000 mB of steam per tick. And yes, that's by design

The idea here is to build more Turbines to use the steam produced by the Reactor(s). 

Keep in mind that I'm talking about the flow rate of the actual coolant ports. If you use pipes between them, the pipe  will dictate the flow rate
